SELECT * FROM costumer_shop.customer_shopping;

-- 1. what is the total revenue generated by male vs female customer?
SELECT gender, sum(purchase_amount) as revenue
FROM costumer_shop.customer_shopping
GROUP BY gender;

-- 2. Which  customers used a discount but still spnet more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM costumer_shop.customer_shopping
WHERE
	discount_applied = 'Yes' 
    AND 
		purchase_amount >= (SELECT AVG(purchase_amount) FROM costumer_shop.customer_shopping)

-- 3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, 
	round(avg(review_rating),2) as "Average Product Rating"
FROM costumer_shop.customer_shopping
GROUP BY item_purchased
ORDER BY AVG(review_rating)DESC
LIMIT 5;

-- 4.  Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
	ROUND(AVG(purchase_amount),2)
FROM costumer_shop.customer_shopping
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
	COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM costumer_shop.customer_shopping
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
	ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM costumer_shop.customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, 
	previous_purchases,
    CASE
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 100 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
	FROM costumer_shop.customer_shopping)
    
    SELECT customer_segment, count(*) AS "Number of Customer"
    FROM customer_type
    GROUP BY customer_segment;
    
    -- 8. What are the top 3 most purchased products within each category? 
   with item_counts AS(
		SELECT category,
				item_purchased,
                COUNT(customer_id) AS total_orders,
                ROW_NUMBER() OVER (
					PARTITION BY category 
                    ORDER BY COUNT(customer_id)DESC
				) AS item_rank
		FROM costumer_shop.customer_shopping
        GROUP BY category, item_purchased
	)
    SELECT item_rank,
		category,
        item_purchased,
        total_orders
	FROM item_counts
    WHERE item_rank <=3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
		COUNT(customer_id) AS repeat_buyers
FROM costumer_shop.customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. what is the revenue contribution of each age group?
SELECT
	age_group,
    SUM(purchase_amount) AS total_revenur
FROM costumer_shop.customer_shopping
GROUP BY age_group
ORDER BY total_revenur DESC;